default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: gold_financial_dev

test:
  <<: *default
  database: gold_financial_test

production:
  <<: *default
  database: gold_financial_production
